name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: fuad1502/verilator-cmake-rust
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set rustup
        run: rustup default stable
      - name: Configure
        run: cmake -Bbuild -S.
      - name: Build
        run: cmake --build build
      - name: Test
        run: cd build && ctest

